Created functionality to direct upload video to vimeo
openvitae-tech/blackboard-lms pull request #188
Opened 2024-11-01 17:39 UTC by paulsojan

Fixes #64

2024-11-05 06:54 UTC, paulsojan commented
@deepakkumarnd Please review

2024-11-06 10:13 UTC, deepakkumarnd requested changes

2024-11-06 10:13 UTC, deepakkumarnd commented on app/controllers/lessons_controller.rb
> +    @lesson = @course_module.lessons.create!(lesson_params)
this results in an exception if the @lesson is invalid and is handled in a rescue block. Isn't the if else statement here is better choice ? From a performance perspective as well ruby exceptions are much slower compared to simple if else statement.

2024-11-06 10:13 UTC, deepakkumarnd commented on app/controllers/lessons_controller.rb
> +  def load_course_module
can we keep this consistent with other loads ? Since we are using set_{resource} everywhere in the code

2024-11-06 10:13 UTC, deepakkumarnd commented on app/controllers/lessons_controller.rb
> +               @lesson.local_contents.first.video
first video need not be the English video, say I upload hindi video first and then english as next video or even say we delete the english video. If params[:lang] we still need to query and load the english video.

2024-11-06 10:13 UTC, deepakkumarnd commented on app/controllers/direct_uploads_controller.rb
> +  protect_from_forgery with: :null_session
don't we need to authenticate admin here ?

2024-11-06 10:13 UTC, deepakkumarnd commented on app/models/lesson.rb
> +  def unique_local_content_lang
you might need to add a unique composite index of lang and lesson_id in local content to prevent this better

2024-11-06 10:13 UTC, deepakkumarnd commented on app/models/local_content.rb
> +  before_create :attach_blob_to_video
Can we avoid these callbacks and keep it in services and call then explicitly, having code in callbacks makes it difficult to reason code and sometimes difficult to test.

2024-11-06 10:13 UTC, deepakkumarnd commented on app/services/upload_video_to_vimeo_service.rb
> +class UploadVideoToVimeoService
In this application I have been following service classes as stateless singleton. Here this class will break that pattern. Could you please make this a singleton ?, if we keep two type of service class in the same directly the code becomes of two styles with two pattern in the same space. Why should we limit services to a single process operation than many meaningful stateless operations ?  

My thought here is to move any statefull operations to dumb model layer and stateless logical operations to services, therefore services shall be kept as singleton no need of new object creation every time you need it. 

```
Lean controllers (keep the business logic but keep its implementation away from controller), 
Dumb models - ask the model to do anything and it will do it except for data integrity
Fat services - Keep the logic implementation in services.
```

One scenario that they say to keep services as non singleton is when you actually have to inject them as a `runtime dependency` (mostly in java I guess that style has been followed in ruby by folks) so that you can avoid code change of some internal function. For example say you want to change `upload_video_to_vimeo_service` to something like `upload_video_to_youtube_service`. In ruby we can easily achive this without any dependency injection by choosing appropriate service at run time.

2024-11-06 10:13 UTC, deepakkumarnd commented on app/services/upload_video_to_vimeo_service.rb
> +    Net::HTTP.start(url.hostname, url.port, use_ssl: true) { |http| http.request(request) }
We should expect failure here and need to add exception handling when connecting to external services.

2024-11-06 10:13 UTC, deepakkumarnd commented on app/services/upload_video_to_vimeo_service.rb
> +      Net::HTTP.start(url.hostname, url.port, use_ssl: true) { |http| http.request(request) }
We should expect failure here and need to add exception handling when connecting to external services.

2024-11-06 10:13 UTC, deepakkumarnd commented on spec/services/upload_video_to_vimeo_service_spec.rb
> +  def upload_to_vimeo_service(blob)
you could use subject {} to define the subject under test at the beginning of the test

subject {   UploadVideoToVimeoService.new(blob)
  end }

2024-11-07 10:01 UTC, paulsojan commented
@deepakkumarnd Made changes. Please review

2024-11-07 12:56 UTC, merged