filter modifications
openvitae-tech/blackboard-lms pull request #447
Opened 2024-12-23 04:46 UTC by sadrisya

2025-01-01 06:59 UTC, paulsojan commented
@sadrisya Please check https://paulsojan.neetorecord.com/watch/24ac8f0c-8c90-45fe-b308-69fa3a18ac76

2025-01-04 05:47 UTC, paulsojan commented
@sadrisya Padding issue in the enrolled course card.
<img width="1261" alt="Screenshot 2025-01-04 at 11 15 20 AM" src="https://github.com/user-attachments/assets/9009eb68-28d5-40fc-9548-c0d85ce08bb8" />

2025-01-04 06:01 UTC, paulsojan requested changes
@sadrisya Please check https://paulsojan.neetorecord.com/watch/dcfb877a801ff3a2b805

2025-01-04 16:04 UTC, sadrisya commented
![Screenshot 2025-01-04 at 9 31 20 PM](https://github.com/user-attachments/assets/a83622bb-18c7-4225-b618-13fd555514ca)
I couldn't see the issue you have mentioned above ,are u running the server using bin/dev ? or rails s

2025-01-06 11:42 UTC, paulsojan commented
@sadrisya I made the changes related to clearing the search term from the URL. Please review the changes and assign the PR to @deepakkumarnd for final review.

2025-01-06 11:43 UTC, paulsojan approved these changes

2025-01-06 12:00 UTC, sadrisya commented
Looks fine

2025-01-07 05:32 UTC, merged